# Generated by Django 5.0.6 on 2024-07-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arya_store', '0002_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.IntegerField(default=0),
        ),
    ]
